load_model: null
conf: null
num_epochs: 3000
batch_size: 300
inference_batch_size: 300
lr: 0.01
lr_patience: 5
lr_min: 1.0e-07
lr_factor: 0.5
lr_warmup_steps: 10000
early_stopping_patience: 500
weight_decay: 0.0
ema_alpha_y: 1.0
ema_alpha_dy: 1.0
ngpus: -1
num_nodes: 1
precision: 32
log_dir: /shared/philipp/geometric/logs/transformer-ANI1/
splits: null
train_size: 0.8
val_size: 0.05
test_size: null
test_interval: 10
save_interval: 10
seed: 10
distributed_backend: ddp
num_workers: 6
redirect: true
dataset: ANI1
dataset_root: ~/data
dataset_arg: null
coord_files: null
embed_files: null
energy_files: null
force_files: null
energy_weight: 1.0
force_weight: 1.0
model: transformer
output_model: Scalar
prior_model: Atomref
embedding_dimension: 256
num_layers: 8
num_rbf: 64
activation: silu
rbf_type: expnorm
trainable_rbf: false
neighbor_embedding: true
distance_influence: both
attn_activation: silu
num_heads: 8
derivative: false
cutoff_lower: 0.0
cutoff_upper: 5.0
atom_filter: -1
max_z: 100
max_num_neighbors: 32
standardize: false
reduce_op: add
prior_args:
  max_z: 100
